# Generated by Django 2.0.4 on 2018-04-20 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('cover', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=200)),
                ('keywords', models.CharField(max_length=200)),
                ('director', models.CharField(max_length=200)),
                ('video', models.CharField(max_length=600)),
                ('budget', models.IntegerField(default=0)),
                ('revenue', models.IntegerField(default=0)),
            ],
        ),
    ]
