# Generated by Django 2.0.4 on 2018-04-20 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_movie_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('avatar', models.CharField(max_length=200)),
                ('gender', models.CharField(default='муж.', max_length=200)),
                ('birth_date', models.CharField(default='1997-08-10', max_length=200)),
                ('birth_place', models.CharField(default='Казахстан', max_length=200)),
                ('about', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='MovieCast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField(default=0)),
                ('cast_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='movie',
            name='about',
            field=models.CharField(default='', max_length=400),
        ),
    ]
