# Generated by Django 2.0.4 on 2018-04-21 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='online',
            field=models.IntegerField(default=0),
        ),
    ]
